# Project information
site_description: Rafay Test Docs site
site_name: Rafay Test Docs Site
site_url: https://darren-rafay.github.io/testdocs/site

# Configuration
theme:
  name: material

# Plugins
plugins:
  - blog:
      enabled: true
      blog_dir: blog/
  - rss:
      match_path: .*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

# Table of Contents
nav:
  - Home: index.md
  - Get Started/Tutorials: learn/overview.md
  - Recipes: recipes/overview.md
  - Releases: releasenotes/overview.md
  - Contact: contact/overview.md
  - Blogs: 
      - blog/index.md